name: markdownlint

on:
  push:
    branches: [main]
    paths:
      - "**/*.md"
      - ".github/workflows/markdownlint.yml"
      - ".markdownlint.json"
  pull_request:
    paths:
      - "**/*.md"
      - ".github/workflows/markdownlint.yml"
      - ".markdownlint.json"

permissions:
  contents: read

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: |
            **/*.md
            !**/node_modules/**
            !InsanityHider/hl2sdk/**
            !InsanityHider/mmsource/**
